@startuml

class Bibloteca {
    - List<Socio> socios
    - VoorheesExporter exporter

    + agregarSocio(Socio socio)
    + exportarSocios(): String
    + getExporter(): VoorheesExporter
    + setExporter(): VoorheesExporter
}

class Socio {
	- String nombre;
	- String legajo;
	- String email;

    + exportarSocio(): JSONObject
	+ getNombre(): String
	+ setNombre(String nombre)
    + getLegajo(): String
    + setLegajo(String legajo)
    + getEmail(): String
    + setEmail(String email)
}

class VoorheesEporteer {

    + exportar(List<Socio> socios): String
}

Bibloteca "0" -- "*" Socio : hace

@enduml