@startuml

class Director {
    +crearPresupuesto(String nombre): Presupuesto
}

class Catalogo {

    +getComponente(descripcion: String): Componente
    +crearBasico(): Computadora
    +crearIntermedio(): Computadora
    +crearGamer(): Computadora
}

abstract Builder {
    +setProcesador(): Componente
    +setMemoriaRam(): Componente
    +setDiscoDuro(): Componente
    +setPlacaVideo(): Componente
    +setFuentePoder(): Componente
    +setGabinete(): Componente
}

abstract BuilderBasico extends Builder {
    +setProcesador(): Componente
    +setMemoriaRam(): Componente
    +setDiscoDuro(): Componente
    +setPlacaVideo(): Componente
    +setFuentePoder(): Componente
    +setGabinete(): Componente
}

abstract BuilderGamer extends Builder {
    +setProcesador(): Componente
    +setMemoriaRam(): Componente
    +setDiscoDuro(): Componente
    +setPlacaVideo(): Componente
    +setFuentePoder(): Componente
    +setGabinete(): Componente
}

abstract BuilderIntermedio extends Builder {
    +setProcesador(): Componente
    +setMemoriaRam(): Componente
    +setDiscoDuro(): Componente
    +setPlacaVideo(): Componente
    +setFuentePoder(): Componente
    +setGabinete(): Componente
}

class Componente {
    - nombre: String
    - descripcion: String
    - precio: double
    - consumo: double

    +getNombre(): String
    +getDescripcion(): String
    +getPrecio(): double
    +getConsumo(): double
}

class Presupuesto {

    +calcularConsumo(): double
    +calcularPrecio(): double
}

Catalogo -right-> Componente : <<BUILDER>> componentes *
Builder -right-> Catalogo : catalogo 1
Presupuesto -up-> Componente : componentes *
Director -right-> Builder : builder 1


@enduml